### ISSUE TITLE
Return error for (*Rows) Scan

### ISSUE THREAD

**Issue by kmyokoyama** [DATA-DOG/go-sqlmock#111]
Is there currently any way of returning an error while scanning?

I am looking for something like

```
rows := NewRows([]string{"id", "title"}).
    AddRow(0, "one").
    AddRow(1, "two").
    ScanError(fmt.Errorf("scan error"))
```

Thanks.

**Comment by l3pp4rd** [comment]
Hi, https://godoc.org/github.com/DATA-DOG/go-sqlmock#Rows.RowError

**Comment by kmyokoyama** [comment]
Hi, thank you. Ok, I see, but what about the error returned by `func (rs *Rows) Scan(dest ...interface{}) error`? Documented [here](https://golang.org/pkg/database/sql/#Rows.Scan).

I imagine a scenario where `rs.Err()` is not called at the end of iteration, but an error actually occurred during `rs.Scan()` (and was returned by it).

Thank you again.

**Comment by l3pp4rd** [comment]
scan can error only based on value type mismatch. so for example if you expect an **int** for column `A` when you mock rows for column `A` to give **[]byte** it should error on rs.Scan, or if you mock less columns than expected by Scan.

**Comment by kmyokoyama** [comment]
Right, does it make sense to mock this kind of error?

**Comment by l3pp4rd** [comment]
yes it makes sense to test whether your error check for Scan is working as expected. and what it does for example when it reads half of rows successfully and fails only for one row, whether you still process results or fail entirely because of single row scan failure. The idea is in general to test how your methods behave in certain cases, which may happen, will it be correct workflow - it does not actually matter what the error is, all matters are the error handling cases and application behavior in these cases.

**Comment by qburst-jyothish** [comment]
Any new updates available in the sqlmock to check whether there is any error during the scan operation.

**Comment by sherzon** [comment]
Is any new updates available in the 'sqlmock' to check whether there is any error occurred during the row scan operation.
