### ISSUE TITLE
Need to trigger Rows.Scan error when using []interface{} as destination

### ISSUE THREAD

**Issue by y-tang** [DATA-DOG/go-sqlmock#122]
Right now, if we have a slice of pointers to `interface{}` as destination for Rows.Scan, we are having trouble trigger Rows.Scan error, since `AddRow` checks if the number of columns provided is the same as the number of columns defined in `NewRow`. As far as I know, the only ways to trigger a Rows.Scan error are 1. column number mismatch and 2. column type mismatch. 

Is it possible to remove the check in `NewRow` so that we can trigger a Rows.Scan error? I'd be happy to learn workarounds. Here is how we are doing the `Scan` using a slice of pointers to interface{}

```
        columns := make([]interface{}, len(columnNames))
	columnPointers := make([]interface{}, len(columnNames))
	for i := range columns {
		columnPointers[i] = &columns[i]
	}

	if scanError := rows.Scan(columnPointers...); scanError != nil {
		return nil, scanError
	}

	record := make(map[string]interface{})
	for i, colName := range columnNames {
		val := columnPointers[i].(*interface{})
		record[colName] = *val
	}
```

**Comment by l3pp4rd** [comment]
Hi, yes we can remove the check, can you submit a pull request?

**Comment by y-tang** [comment]
Will do. Thanks!

**Comment by y-tang** [comment]
I did more testing after removing the check and found out removing the check won't enable us to trigger a Scan Error ;( Please feel free to close the issue. Here are some details if anyone is interested to know:

If we supply more columns in `AddRow` than what we specify in `NewRow`, this would cause an index-out-of-range error in `Next`, since `sql` constructs a slice with length of columns specified in `NewRow` as capacity and pass it along to `Next`

If we supply less columns in `AddRow` than what we specify in `NewRow`, this would just result in some columns having `nil` value. We can accomplish the same thing by explicitly providing `nil` in `AddRow`.
So I don't think we need the proposed change ;( And I am still looking for possible workarounds to trigger a ScanError when using a slice of pointers to `interface{}`s as destination in `Scan`

And BTW, thanks for responding to the issue so quickly!

**Comment by l3pp4rd** [comment]
thanks @y-tang for explaining it, someone might find it useful if going through the same process. So in the end as far as I understand it will not trigger the scan error in actual database either if using pointers. If actual database cannot trigger a scan error, then in your specific test scenario, there is no need to test it. Though, if query rows were used, it may hold a connection and scan could result in broken connection in real life, but I'm not certain about it, probably if such error could be triggered, it would make sense to have it mockable. But maybe it would be just a rows.Err() instead of scan error.
