### ISSUE TITLE
Force errors in other places

### ISSUE THREAD

**Issue by hgfischer** [DATA-DOG/go-sqlmock#13]
I would like to force errors in other places such as:

```
http://golang.org/pkg/database/sql/#Rows.Scan
http://golang.org/pkg/database/sql/#Rows.Columns
```

Are there any plans about this?

**Comment by arvenil** [comment]
+1, any plans for that?

**Comment by l3pp4rd** [comment]
hi, yes, that is a reasonable request. cannot make any promises when I will take some time to do it, but it should be within two weeks ;) if you need that sooner, I'm open for the pull request if it remains BC.

**Comment by karlkfi** [comment]
+1

Also would like to be able to force `http://golang.org/pkg/database/sql/#Rows.Next` to fail.

**Comment by l3pp4rd** [comment]
sorry, for the delay, but I'm currently extremely busy, hope that can wait a little longer.

**Comment by l3pp4rd** [comment]
currently I am working with a concurrency support and other issues. concerning columns error mocking - there is no way for error to occur, see [source](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1659) unless you close rows or driver gives nil instead of rows. This error may occur only in these cases. this may be considered later, since it won't break BC. Other places: rows.Close, rows.Next will be supported in next version

**Comment by l3pp4rd** [comment]
by the way, to mock scan errors simply add rows with unsupported type for scan. see [test](https://github.com/DATA-DOG/go-sqlmock/blob/refactor/rows_test.go#L183) as an example
