### ISSUE TITLE
Add `ExpectAnything` to sqlmock

### ISSUE THREAD

**Issue by s4t13** [DATA-DOG/go-sqlmock#155]
Hi, 

First of, thanks for the plugin, it's great 👍 

I discovered that for some of my tests I need a database driver but I don't really care about what happens on it (i.e. the logic of the application is tested, not the queries). I was wondering if a method could be added so that the mock would accept anything until the connection is closed.

```golang
// not actual go code, may be faulty
func TestingLogicNotDB(t *testing.T){
    db, mock, err := sqlmock.New()
    defer db.Close()
    mock.ExceptAnything()
    
   // testing using db
}
```

I haven't looked at the code yet, so I don't know how feasible it would be to implement something like that, but if it can be of any value I can try to spend some time doing it.

Best,

**Comment by l3pp4rd** [comment]
Hi, this is a poor suggestion, how can you expect anything? if code you are running expects a selected row present, sqlmock needs to know what rows to return, how many columns it should have and etc.

In general, sqlmock will not even attempt to provide any similar behavior you are describing. It simulates the SQL driver from go standard library.

When you submit a suggestion like that, please try to understand it first, or better try implementing it in order to understand the reasoning. But maybe I got your suggestion wrong?

**Comment by alenn-m** [comment]
Hi

I need a similar thing, so didn't want to open a new issue.
Basically, I'm testing a sign-up endpoint, and inside that endpoint, there is a bcrypt hash, so I can't just add `.WithArgs("somepassword")` since the hashed password will always be different. Is there anything I can add to check if the argument is a string, I don't need to know exact string.

**Comment by l3pp4rd** [comment]
@alenn-m [read the manual](https://github.com/DATA-DOG/go-sqlmock#matching-arguments-like-timetime) ref in [godoc](https://godoc.org/github.com/DATA-DOG/go-sqlmock#Argument)

**Comment by alenn-m** [comment]
Thanks a lot

**Comment by s4t13** [comment]
@l3pp4rd thanks for the reply, I get what you mean. I asked the question exactly to understand if it would be something possible / a good idea.

It's not, case closed 👍

**Comment by felix9ia** [comment]
time.Time can use ` monkey.Patch` in   `TestMain`


 https://bou.ke/blog/monkey-patching-in-go/
```
	

func TestMain(m *testing.M) {
	setup()
	code := m.Run()
	teardown()
	os.Exit(code)
}

func setup() {
	monkey.Patch(time.Now, func() time.Time {
		return time.Date(2009, 11, 17, 20, 34, 58, 651387237, time.UTC)
	})
}
```
