### ISSUE TITLE
QueryRow doesn't satisfy expectation

### ISSUE THREAD

**Issue by jamesbloomer** [DATA-DOG/go-sqlmock#16]
My function calls QueryRow, in the test I've set up an ExpectQuery as if it were a normal Query. The QueryRow does not appear to satisfy the expectation. Is that expected?

**Comment by l3pp4rd** [comment]
well, you should first look into the tests of this library in order to see whether your question has a point. the answer would be - it must be your mistake if it doesn't [see](https://github.com/DATA-DOG/go-sqlmock/blob/master/sqlmock_test.go#L214), please be kind and investigate more, before submitting a question like that, correct me, if I understood the question in a wrong way. cheers mate.

**Comment by jamesbloomer** [comment]
Thanks. Yep, should have checked your tests, sorry about that.
