### ISSUE TITLE
How to test mysql statments using the LIMIT clause?

### ISSUE THREAD

**Issue by JairoGLoz** [DATA-DOG/go-sqlmock#184]
I'm writing some tests for mysql queries that use the LIMIT clause.

I'm defining a set of, let's say, 5 rows for my mock to return when a "select (.+) from table" query is executed. The actual query is something like "select * from table limit 1,3" so I'm supposed to get 3 rows (from 1 to 3, since it's a 0 indexed array). However I'm getting the 5 rows.

Is there a way to test this behavior or am I supposed to just return the 3 rows I'm expected directly?

**Comment by l3pp4rd** [comment]
Hi, it seems you do not understand what sqlmock does and is meant to do.
If you mock it to return 5 rows - it will, no matter what query you will give. Sqlmock or sql/driver standard library does not parse the queries, it just sends them to the driver implementation. And sqlmock is a mocking driver implementation.
So you should return 3 rows as you'd expect, because the underlying SQL driver you use will certainly react to the LIMIT clause, sqlmock will not.

**Comment by JairoGLoz** [comment]
Got it, thanks.
