### ISSUE TITLE
Is there a way to use v1 in combination with GORM?

### ISSUE THREAD

**Issue by christianklotz** [DATA-DOG/go-sqlmock#24]
The previous version allowed to simply pass the `mock` driver name to the [GORM](https://github.com/jinzhu/gorm) initialiser. Since the new version doesn't expose any interface to set the `sql.DB` instance and GORM not doing so either (see this [issue](https://github.com/jinzhu/gorm/issues/72)) I couldn't figure out a way to test.

Is there a way or do I have to rethink my testing approach?

**Comment by l3pp4rd** [comment]
Well, probably we could expose method like `NewWithDSN(dsn string)` when you would have the mock for mocking. and calling gorm with the same dsn it would open the same database connection since dsn is the same, [see](https://github.com/DATA-DOG/go-sqlmock/blob/master/driver.go#L44). But I will need to think about it more, whether it is reasonable to implement it this way, you can make a fork for now.
For example sqlx package provides a method to initialize with DB and driver name.

**Comment by l3pp4rd** [comment]
The method needed would look like:

``` go
func NewWithDSN() (db *sql.DB, mock Sqlmock, err error) {
	pool.Lock()
	smock := &sqlmock{dsn: dsn, drv: pool, ordered: true}
	pool.conns[dsn] = smock
	pool.Unlock()

	db, err = sql.Open("sqlmock", dsn)
	if err != nil {
		return
	}
	return db, smock, db.Ping()
}
```
