### ISSUE TITLE
Arguments Error

### ISSUE THREAD

**Issue by afzalabbasi** [DATA-DOG/go-sqlmock#264]
hey All
mock.ExpectExec("SELECT * FROM permission WHERE roleid = $1").WithArgs(2) this is my mock queey i just compare that one with the original  query which one is db.Get(&programinfo, "SELECT * FROM permission WHERE roleid = $1", roleid)
but i found that error 
call to Query 'SELECT * FROM permission WHERE roleid = $1' with args [{Name: Ordinal:1 Value:2}], was not expected, next expectation is: ExpectedExec => expecting Exec or ExecContext which:
  - matches sql: 'SELECT * FROM permission WHERE roleid = $1'
  - is with arguments:
there is a remaining expectation which was not matched: ExpectedExec => expecting Exec or ExecContext which:
        	            	  - matches sql: 'SELECT * FROM permission WHERE roleid = $1'
        	            	  - is with arguments:
        	            	    0 - 2
  Can SomeOne please help me how i fixed this issue
Thanks

**Comment by dolmen** [comment]
Please post some example code working on the Go Playground. Here is [a template](https://go.dev/play/p/CKPijIE9iYe).

**Comment by ShuaoZhang** [comment]
Same issue, have you fixed it?

**Comment by diegommm** [comment]
Hi @afzalabbasi! It looks like you're using `ExpectExec` for a SELECT, which should typically be modeled with a `Query`, `QueryContext`, `QueryRow`, `QueryRowContext`. The code you provide is using a `Get` method, which is not part of the standard library's `database/sql` package, so it's harder to know what your `Get` method is doing. Maybe you're using a wrapper library like gorm or sqlx? If that's the case and your wrapper library is transalting to any of the 4 `Query`* methods then you should use `ExpectQuery` instead of `ExpectExec`.

I hope that helps, closing as this seems related to usage of an external library. If the problem persists, reopen and provide the following information:

- Your `sqlmock` version.
- Example code working on the Go Playground. Example: https://go.dev/play/p/CKPijIE9iYe (thanks @fatelei!).
- If you use any wrapping libraries (like gorm, sqlx, etc.), their names and version.

Thank you!
