### ISSUE TITLE
how to mock mock preload 

### ISSUE THREAD

**Issue by ShuaiGao** [DATA-DOG/go-sqlmock#302]
### Question

I'm always confused about preload, can you add more usage examples, one-to-one and one-to-many examples

**Comment by diegommm** [comment]
Hi @ShuaiGao! Closing as there is not enough information to help you, unfortunately. It would appear you are referring to the GORM library? If so, consider that it's a separate library that is unrelated to `sqlmock`, and it has a completely different approach. GORM can help you do fast prototyping and generate a lot of code for you, but you lose some control on what SQL code is being run and how. This means that GORM adds an abstraction layer that you have to account for. Consider the following instead:

- GORM is a higher level tool that already has tests that covers the generated SQL.
- Mock the GORM library and use that mock to test that a certain GORM-specific operation is carried out.
- Changes to the GORM library may affect the SQL it generates, hence invalidating many or all of your tests.
- If you really care to test for the SQL code you run (and you may not for small projects, and that's fine), consider switching to `database/sql` instead and building the SQL code so that the code you run is predictable and deterministic.
- Otherwise you will be trying to guess what GORM generated for you in that abstraction layer, and you may have to resort to reading the code in GORM to understand that.

Thank you!
