### ISSUE TITLE
Allow generous matching when SELECTing nondeterministic data

### ISSUE THREAD

**Issue by kinoru** [DATA-DOG/go-sqlmock#40]
Thanks for an awesome library. I couldn't find a solution to this issue, and hope there's a trivial answer I couldn't reach.

I'm trying to test a function that executes a `SELECT` query which will return a row that contains a nondeterministic datum. The nondeterministic datum could be as simple as a timestamp, or as complex as a system process information that was inspected at the moment of `INSERT`.

Executing a query without `Expect...` is forbidden:

```go
all expectations were already fulfilled, call to query '...'  was not expected
```

The `Expect...` series, such as `ExpectQuery`, requires a call to `WillReturnRows` or `WillReturnError`. Otherwise, it seems, it's an error:

```go
query '...' must return a database/sql/driver.rows, but it was not set for expectation
*sqlmock.ExpectedQuery as ExpectedQuery => expecting Query or QueryRow
...
```

But `WillReturnRows` requires a _precise_ row that will be used for an exact matching. The trouble is, I don't know what the precise row would be, because it contains a nondeterministic field.

There is a guide for matching _arguments_ in [README.md], but they are used for matching the _query_ - what is to be **sent** to the database. I need a generous way to match the _query result_ - what is to be **received** from the database.

Naturally, the solution for _arguments_ doesn't work for matching the query result. The following:

```go
rows := sqlmock.NewRows([]string{
	"id", "some_nondeterministic_field"}).
	AddRow(1, sqlmock.AnyArg())
mock.ExpectQuery(readQuery).WillReturnRows(rows)
```

is an error:

```go
sql: Scan error on column index 1: converting driver.Value type sqlmock.anyArgument (\"{}\") to a uint64: invalid syntax
```

In fact I'd be happy to let sqlmock not do any kind of matching at all. I'd be grateful if I could just execute queries to the `db` object, get the result from my function, and do the matching myself.

Any idea?

[README.md]: https://github.com/DATA-DOG/go-sqlmock/blob/11d3eed60093ee56557808d51b784aea8b50b422/README.md#matching-arguments-like-timetime

**Comment by l3pp4rd** [comment]
Hi thanks, the rows mocked for sqlmock must be deterministic at least in a way to match your scanner used to read results. your nondeterministic field must still have a valid database type and you can mock any kind of value for it, so you rows.Scan could read it.
So if your field value maps to `[]byte` you should mock it to at least an empty byte array, if it is a string - any kind of string and so on. you should create that value if it is read by your implementation. Imagine sqlmock as a virtual database, where you say what to return in which situation.
Sqlmock, cannot interfere which production (non test code) to match result in custom ways, because it just replicates your sql database behavior.

**Comment by kinoru** [comment]
You clarified the point for me. Thanks for such a quick and enlightening response!
