### ISSUE TITLE
go-sqlmock, ExpectQuery not working for gorp SelectOne?

### ISSUE THREAD

**Issue by dvwright** [DATA-DOG/go-sqlmock#46]
Hi, as stated in the title, I am having an issue testing an api endpoint with ExpectQuery. I am using the 'Gin' framework.

This is not working as expected:

`mock.ExpectQuery("^SELECT (.+) FROM user where id=? LIMIT 1$").WithArgs(1).WillReturnRows(rows)`

it's failing and returning:

`query 'SELECT * FROM user WHERE id=? LIMIT 1', does not match regex [^SELECT (.+) FROM user where id=? LIMIT 1$]`

I have created a gist here which reproduces the issue. https://gist.github.com/dvwright/490ed14a72ae7dab818026b1081f689c

The 'TestGetUsers' test passes, the 'TestGetSpecificUser' test does not pass.

I am new to golang so please feel free to point out user error, or another way to accomplish my goal.

Thanks

**Comment by l3pp4rd** [comment]
Hi, since you know that sqlmock accepts regular expression strings, I suggest you read how to properly escape and match your queries, they are case sensitive.

`mock.ExpectQuery("^SELECT \\* FROM user WHERE id=\\? LIMIT 1$").WithArgs("1").WillReturnRows(rows)`

Since you make only a single query in that request, I suggest you to match it like `^SELECT \\* FROM user`.

this library is well tested and used. it is highly unlikely for you to find a bug in such a common use case.

**Comment by dvwright** [comment]
Yes, thank you, I forgot to escape the '?'.
