### ISSUE TITLE
Checking correctness of query sintax

### ISSUE THREAD

**Issue by Gujarats** [DATA-DOG/go-sqlmock#64]
suppose I've made mistake on writing the query on both of the mock and the real query for insert data. For example : 
	`mock.ExpectExec("INSER INTO table").WithArgs("2017-12-21", 1234).WillReturnResult(sqlmock.NewResult(1, 1))
`

and the query sintax : 

	
	buff := bytes.NewBufferString(`
            INSER INTO table(
                date,
                shop_id
            ) VALUES ($1, $2)
        `)
	query := txShop.Rebind(buff.String())
	_, err = txShop.Exec(query, Date, shopIdInt)

Notice that I wrote the wrong sintax on `INSER` it should be `INSERT`. is there any way to add new checking algorithm of sintax query?

**Comment by l3pp4rd** [comment]
there is a lot about syntax here, go sql.driver also does not check the syntax. and there is a valid reason, you have to take into account all available sql drivers because each of them has their own syntax sugar apart from SQL standards. It never can be correct in all circumstances or too complex to maintain. If we add sql standard syntax support, then people start to request their used driver support.
I'll try to follow go's advice about simplicity and do one thing well. or if someone releases a package to wrap sql driver for syntax correction checks, then I'll allow to use it in this package.
In general it should be a different SQL driver, which wraps wanted driver for syntax correction checks. and though a different package and maintainer.
