### ISSUE TITLE
Disable/limit expectations?

### ISSUE THREAD

**Issue by ryanberckmans** [DATA-DOG/go-sqlmock#66]
Is it possible to disable or limit that expectations were met? I'm happy just to have a db mock which allows my transactional code to be unit tested. Is there another way I should be doing this?

**Comment by l3pp4rd** [comment]
Hi., you are the first one to complain about correctness of sqlmock. I do not see any valid reasons, why it should allow to bypass some of the sql operations, these might lead to unexpected bugs. go is pragmatic language, don't worry if you repeat your code few times. Otherwise extract your transaction code into a separate function. or do not assert expectations at all :) this is not a problem of sqlmock

**Comment by ryanberckmans** [comment]
It wasn't intended as a complaint :). Our queries are auto-generated by a library and are difficult and brittle to translate into expectations.

sqlmock looks great. Disabling certain expectations would allow us to use it sooner and in more places. I can see how this use case isn't needed by others.

**Comment by l3pp4rd** [comment]
I will remain in strict position about expectations, because it ensures correctness. If I'll add such an option, to match only some of the expectations, users may unintentionally develop some bugs. My suggestion is to always use standard sql library, if your tool generates many sql queries or cumbersome methods then it is not a problem of sqlmock. It simply does what it should and will remain to do so. You can fork this library and adapt for your use cases, but it is not something which should be implemented as a core feature.

**Comment by ryanberckmans** [comment]
I understand, thanks for the discussion.
