### ISSUE TITLE
Polish code example

### ISSUE THREAD

**Issue by Vitucho** [DATA-DOG/go-sqlmock#85]
Hi there, i was reading your readme file, and i was wondering if in the example function to test the defer functon should be moved to the end. Recall that defer (from effective-go) 

> The arguments to the deferred function (which include the receiver if the function is a method) are evaluated when the defer executes, not when the call executes
```

func recordStats(db *sql.DB, userID, productID int64) (err error) {
	tx, err := db.Begin()
	if err != nil {
		return
	}

	if _, err = tx.Exec("UPDATE products SET views = views + 1"); err != nil {
		return
	}
	if _, err = tx.Exec("INSERT INTO product_viewers (user_id, product_id) VALUES (?, ?)", userID, productID); err != nil {
		return
	}

        // place it over here
	defer func() {
		switch err {
		case nil:
			err = tx.Commit()
		default:
			tx.Rollback()
		}
	}()

	return
}
```

So i guess that way the err will also behold the errors of the execs queries.
Please excuse me for the probably annoying observation i am making here, hope it helps, in any way.

Greetings!

**Comment by l3pp4rd** [comment]
Hi, actually, we cannot move it to the end, because we need to rollback transaction in case of the error. In case if one of Exec fails, defer will catch error and rollback. Maybe go would rollback it too when **tx** is garbage collected, but it would take some time for GC to kick in, and though **tx** reserves database connection.

The code is correct in the example, though, it may not be the best option to use it that way, most likely you would want to pass in **Execer** interface to this method instead of `*sql.DB` directly and start the transaction elsewhere.

I think it would be much more confusing to move defer statement and it questions correctness.

**Comment by Vitucho** [comment]
my Bad! and please excuse me. Thanks for the observation and the reply!.
Greetings.
