### ISSUE TITLE
Proper way to mock a stored procedure in postgres

### ISSUE THREAD

**Issue by kristen1980** [DATA-DOG/go-sqlmock#93]
I have a stored procedure that one of my functions relies on. To mock this stored procedure I am doing:

    mock.ExpectExec(`
	CREATE OR REPLACE FUNCTION val() RETURNS INT AS
	    $$
	    SELECT 1;
	    $$
	LANGUAGE sql;
    `,
	).WillReturnResult(sqlmock.NewErrorResult(nil))

	if err := mock.ExpectationsWereMet(); err != nil {
	  t.Fatal(err)
	}

This fails with the following:

    there is a remaining expectation which was not matched: ExpectedExec => expecting Exec which:
    	 - matches sql: 'CREATE OR REPLACE FUNCTION val() RETURNS INT AS $$ SELECT 1; $$ 
    LANGUAGE sql;'
    	 - is without arguments
    	 - should return Result having:
    	     LastInsertId: 0
    	     RowsAffected: 0

I've also tried other ways but just am not sure how to mock this stored procedure. To be clear, I am testing a function that calls val(). (And maybe I am travelling down the wrong path...I just need to be able to call val()). More details: https://stackoverflow.com/questions/46311546/mocking-postgresql-with-a-stored-procedure

**Comment by l3pp4rd** [comment]
Hi, in order to be sure, that your expression is correct or not, reduce it like `mock.ExpectExec("CREATE OR REPLACE FUNCTION val")` my guess is that your regexp is not valid, symbols like `($` needs escaping since every query is converted to regexp. And check later how to properly escape regular expressions.

**Comment by l3pp4rd** [comment]
next, I would never recommend to have procedures. if you scale your datatabase, only one will be able to have these procedures which modifies tables for example, otherwise it would execute the number of times there are machines. recommendation is to avoid using procedures in database, business logic should be in application not in database.
